const fs = require('fs-extra');
const path = require('path');

const viewsDirectory = path.join(__dirname, 'views'); // Path to the views directory

const files = fs.readdirSync(viewsDirectory); // Get all files in the views directory

const autoGeneratedPaths = files
  .filter((file) => fs.lstatSync(path.join(viewsDirectory, file)).isDirectory()) // Filter out directories
  .map((directory) => {
    return {
      path: `/${directory}`,
      element: require(path.join(viewsDirectory, directory)).default,
    };
  });

module.exports = { paths: autoGeneratedPaths };
